name: Build Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build_for_windows:
    name: Build for Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if (Test-Path requirements.txt -PathType Leaf) { pip install -r requirements.txt }
      - name: Build binary
        run: |
          pyinstaller --onefile --windowed --add-data "header.png;." --add-data "icon.ico;." --add-data "left.png;." --add-data "LICENSE;." --add-data "metadata.json;.\\component_pack" main.py
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: installer windows.exe
          path: ./dist/main.exe
  build_for_linux:
    name: Build for linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build binary
      run: |
        pyinstaller --onefile --windowed --add-data "header.png;." --add-data "icon.ico;." --add-data "left.png;." --add-data "LICENSE;." --add-data "metadata.json;.\\component_pack" main.py
    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: installer linux
        path: ./dist/main